---
- name: install | Create temporary working directory
  ansible.builtin.tempfile:
    state: directory
    suffix: temp
  register: _workdir

- name: install | Download matchbox release and signature
  ansible.builtin.get_url:
    url: "{{ matchbox_download_url }}/{{ item }}"
    dest: "{{ _workdir.path }}/{{ item }}"
    mode: "0600"
  loop:
    - "{{ matchbox_tarball }}"
    - "{{ matchbox_signature }}"

- name: install | Import signing key - {{ matchbox_signing_key }}
  ansible.builtin.command: gpg --keyserver keyserver.ubuntu.com --recv-key {{ matchbox_signing_key }}
  register: _result
  changed_when: _result.rc != 0
  environment:
    GNUPGHOME: "{{ _workdir.path }}"

- name: install | Verify download
  ansible.builtin.command: gpg --verify {{ matchbox_signature }} {{ matchbox_tarball }}
  register: _result
  changed_when: _result.rc != 0
  args:
    chdir: "{{ _workdir.path }}"
  environment:
    GNUPGHOME: "{{ _workdir.path }}"

- name: install | Extract download
  ansible.builtin.unarchive:
    src: "{{ _workdir.path }}/{{ matchbox_tarball }}"
    dest: "{{ _workdir.path }}"
    remote_src: true

- name: install | Move matchbox binary to {{ matchbox_bin_directory }}
  ansible.builtin.copy:
    src: "{{ _workdir.path }}/{{ matchbox_release_name }}/matchbox"
    dest: "{{ matchbox_bin_directory }}"
    remote_src: true
    mode: "0755"

- name: install | Remove temporary working directory
  ansible.builtin.file:
    path: "{{ _workdir.path }}"
    state: absent
