---
- name: Include variables
  ansible.builtin.include_vars: main.yml

- name: Check matchbox version
  ansible.builtin.command: "{{ matchbox_bin_directory }}/matchbox --version"
  register: _result
  changed_when: _result.rc != 0
  # 'Errno 2' is 'file not found' - which is expected if matchbox isn't installed
  failed_when: >
    (_result.rc != 0) and
    ('Errno 2' not in _result.msg)

- name: Install matchbox binary
  ansible.builtin.include_tasks: install.yml
  when: _result.rc != 0 or _result.stdout != matchbox_version

- name: "Create group - {{ matchbox_group }}"
  ansible.builtin.group:
    name: "{{ matchbox_group }}"
    state: present

- name: "Create user - {{ matchbox_user }}"
  ansible.builtin.user:
    name: "{{ matchbox_user }}"
    group: "{{ matchbox_group }}"
    state: present

- name: Create matchbox directories
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ matchbox_user }}"
    group: "{{ matchbox_group }}"
    mode: "0750"
  loop:
    - "{{ matchbox_data_path }}"
    - "{{ matchbox_assets_path }}"
    - "{{ matchbox_config_path }}"

- name: Create matchbox configuration file
  ansible.builtin.template:
    src: sysconfig.j2
    dest: /etc/sysconfig/matchbox
    owner: root
    group: root
    mode: '0444'

- name: Create matchbox systemd service file
  ansible.builtin.template:
    src: matchbox.service.j2
    dest: /etc/systemd/system/matchbox.service
    owner: root
    group: root
    mode: '0444'
  notify:
    - Daemon reload

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure matchbox is started and enabled (if configured)
  ansible.builtin.service:
    name: "{{ matchbox_daemon }}"
    state: "{{ matchbox_state }}"
    enabled: "{{ matchbox_enabled }}"