---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: el8
    image: quay.io/rockylinux/rockylinux:8
    pre_build_image: true
  - name: el9
    image: quay.io/rockylinux/rockylinux:9
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
