---
# This is an example playbook to execute Ansible tests.
# TODO verify web+ssl/gRPC
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Test the default matchbox server endpoint
      ansible.builtin.uri:
        url: http://localhost:8080
        method: GET
        return_content: true
      register: _response

    - name: Verify response from matchbox
      ansible.builtin.assert:
        that: "(_response.content | trim) == 'matchbox'"
