---
# This is an example playbook to execute Ansible tests.
# TODO verify web+ssl/gRPC
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Initialize role
      ansible.builtin.include_role:
        name: matchbox
        tasks_from: init
        public: true

    - name: "Test {{ matchbox_web_ssl | ternary('https', 'http') }}://{{ matchbox_address }}"
      ansible.builtin.uri:
        url: "{{ matchbox_web_ssl | ternary('https', 'http') }}://{{ matchbox_address }}"
        method: GET
        validate_certs: false
        return_content: true
      register: _response

    - name: Verify server response
      ansible.builtin.assert:
        that: "(_response.content | trim) == 'matchbox'"
